version: '3'

services:
  web:
    image: python-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:9999"
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    expose:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
